# Generated by Django 2.0.2 on 2018-02-04 09:33

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('displayName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemOnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shopperHelper.item')),
            ],
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupAssigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupAssigned', to='shopperHelper.group')),
                ('items', models.ManyToManyField(to='shopperHelper.item')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='shopperHelper.user'),
        ),
        migrations.AddField(
            model_name='itemonreceipt',
            name='receiptMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiptMaster', to='shopperHelper.receipt'),
        ),
        migrations.AddField(
            model_name='itemonreceipt',
            name='usersToSplit',
            field=models.ManyToManyField(to='shopperHelper.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='groupOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupOwner', to='shopperHelper.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='shopperHelper.user'),
        ),
    ]
