# Generated by Django 2.0.3 on 2018-07-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('displayName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOnReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shopperHelper.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='receipt_images/None/no-image.jpg', upload_to='receipt_images/')),
                ('receiptID', models.CharField(blank=True, max_length=200)),
                ('groupAssigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupAssigned', to='shopperHelper.Group')),
                ('items', models.ManyToManyField(to='shopperHelper.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='shopperHelper.User'),
        ),
        migrations.AddField(
            model_name='itemonreceipt',
            name='receiptMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiptMaster', to='shopperHelper.Receipt'),
        ),
        migrations.AddField(
            model_name='itemonreceipt',
            name='usersToSplit',
            field=models.ManyToManyField(to='shopperHelper.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='groupOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupOwner', to='shopperHelper.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='shopperHelper.User'),
        ),
    ]
