# Generated by Django 2.0.1 on 2018-02-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopperHelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='STUDENT', max_length=100),
        ),
    ]
