# Generated by Django 2.0.2 on 2018-02-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopperHelper', '0007_auto_20180204_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(default='receipt_images/None/no-image.jpg', upload_to='receipt_images/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupOwner', to='shopperHelper.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='shopperHelper.User'),
        ),
        migrations.AlterField(
            model_name='itemonreceipt',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shopperHelper.Item'),
        ),
        migrations.AlterField(
            model_name='itemonreceipt',
            name='receiptMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiptMaster', to='shopperHelper.Receipt'),
        ),
        migrations.AlterField(
            model_name='itemonreceipt',
            name='usersToSplit',
            field=models.ManyToManyField(to='shopperHelper.User'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='groupAssigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupAssigned', to='shopperHelper.Group'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.ManyToManyField(to='shopperHelper.Item'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='shopperHelper.User'),
        ),
    ]
