# Generated by Django 2.0.1 on 2018-03-03 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopperHelper', '0014_auto_20180303_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupOwner', to='shopperHelper.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='shopperHelper.User'),
        ),
        migrations.AlterField(
            model_name='itemonreceipt',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shopperHelper.Item'),
        ),
        migrations.AlterField(
            model_name='itemonreceipt',
            name='receiptMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiptMaster', to='shopperHelper.Receipt'),
        ),
        migrations.AlterField(
            model_name='itemonreceipt',
            name='usersToSplit',
            field=models.ManyToManyField(to='shopperHelper.User'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='groupAssigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupAssigned', to='shopperHelper.Group'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='items',
            field=models.ManyToManyField(to='shopperHelper.Item'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='shopperHelper.User'),
        ),
    ]
